POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImlhdCI6MTc1MzU1MjkxOSwiZXhwIjoxNzUzNjM5MzE5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.UXjHky24h56896foIJ39FFoIvRMcJ1kX7NEgw1BZ7HU"
}